version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/fintechDB
    depends_on:
      - mongo
  frontend:
    build: ./frontend/axis-fe
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/axis-fe:/app
      - /app/node_modules
    depends_on:
      - backend
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
